package handlers

import (
	model "assignment-2/internal/models"
	"assignment-2/internal/utils"
	//"assignment-2/internal/store"
	"crypto/md5"   //for generarting hash to create api key
	"encoding/hex" //for converting md5 hash to string
	"encoding/json"
	"fmt" //for writing output and testing
	"net/http"
	"net/mail" //for email check (private emails also accepted)
	"time"     //time of creating api key and for generating unique api key based partly on time hash
)

type Login struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Key struct {
	ApiKey    string `json:"key"`
	CreatedAt string `json:"createdAt"`
}

/*
This function is the handler for the /register endpoint, it is responsible for handling the registration of users and generating API keys for them.
The function first checks if the request method is POST, if not, it returns a method not allowed error.
Then it parses the JSON body of the request into a Login struct, and validates the input (check if name and email are not empty, and if email contains @).
If the input is valid, it generates an API key for the user by calling the createAPIKey function, and checks if the generated API key is already in use by calling the isAPIKeyUsed function.
If the API key is unique, it encodes the key struct to JSON and sends it back to the user as a response.

@param w - the http.ResponseWriter used to send the response back to the client
@param r - the http.Request containing the details of the incoming request, including the JSON body with the user's name and email

@see createAPIKey - the function responsible for generating a unique API key for the user
@see isAPIKeyUsed - the function responsible for checking if the generated API key is already in use and not empty or incomplete
*/
func (h *Handler) RegisterAuth(w http.ResponseWriter, r *http.Request) {
	//used in handling connection to Firestore
	ctx := r.Context()

	if r.Method != http.MethodPost { //if not a POST request, return method not allowed
		http.Error(w, "Only POST method allowed", http.StatusMethodNotAllowed)
		return
	}

	// Parse the JSON body of the request into a Login struct
	var login Login
	defer r.Body.Close()

	err := json.NewDecoder(r.Body).Decode(&login)
	if err != nil {
		http.Error(w, "Invalid JSON format", http.StatusBadRequest)
		return
	}

	// Validate the input (check if name and email are not empty, and if email contains @)
	if login.Email == "" || login.Name == "" {
		http.Error(w, "Missing name or email", http.StatusBadRequest)
		return
	}

	//check if email is correctly formated (RFC 5322), if not, return bad request
	if !isValidEmail(login.Email) {
		http.Error(w, "Invalid email format", http.StatusBadRequest)
		return
	}

	//getting how manny api keys the user alreaddy have to confirm is they can make more
	howMannyApiKeys, err := h.store.CountApiPerUser(ctx, login.Email)
	if err != nil {
		http.Error(w, "fault reaching Firestore", http.StatusInternalServerError)
		return
	}
	if (howMannyApiKeys) > utils.MAXAPIKEYS-1 {
		http.Error(w, "To manny api keys registerd to this user, try deleting one", http.StatusTooManyRequests)
		return
	}

	// Generate API key for the user
	var createAPI, timeCreateApi string
	//maxAttempt should be a const, but I want to ask team member or TA for what is a reasonable number
	//max attempt is used to avoid loop with checking api key duplicate!
	maxTestAttempts := 10
	for i := 0; i < maxTestAttempts; i++ {
		createAPI, timeCreateApi = createAPIKey(login.Email)
		if !h.store.ApiKeyExists(ctx, createAPI) {
			break
		}
		//this would only be in the senario where some number breakes the md5 hash or full storage in database
		//then it would be an infinte loop of generating api keys, this should not happen, so we want to break this after a certain number of attempts and log it
		if i == maxTestAttempts-1 {
			fmt.Printf("Failed to generate a unique API key after %d attempts\n", i+1)
			http.Error(w, "Failed to generate a unique API key after several attempts", http.StatusLoopDetected)
			return
		}
	}

	//formatting the response to the user, which includes the generated API key and the time of API creation
	keyResponse := Key{
		ApiKey:    createAPI,
		CreatedAt: timeCreateApi,
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	if err := json.NewEncoder(w).Encode(keyResponse); err != nil {
		http.Error(w, "Failed to encode response", http.StatusInternalServerError)
		return
	}

	reg := model.Authentication{
		Name:      login.Name,
		Email:     login.Email,
		ApiKey:    keyResponse.ApiKey,
		CreatedAt: timeCreateApi,
	}
	err = h.store.CreateApiStorage(ctx, reg)
	if err != nil {
		http.Error(w, "Failed to save api keys in Firestore", http.StatusInternalServerError)
		return
	}
}

/*
This function generates an API key for the user based on their email and the current time.
The API key is generated by creating a hash of the email and the current time using md5, and then encoding it to a string.
The API key is prefixed with "sk-envdash-" to make it more recognizable as an API key and .
The function also returns the time of API creation, which is formatted according to the specifications in the assignment.
This allows us to keep track of when the API key was created, which can be useful for expiration or auditing purposes.

@param email - the email of the user for whom the API key is being generated
@return createAPI - the generated API key for the user
@return timeCreateApi - the time of API creation, formatted according to the specifications in the assignment
*/
func createAPIKey(email string) (string, string) {

	timeCreateApi := time.Now().Format("20060102 15:04") //this is the format specified in the assignement for time
	fmt.Println("Time of API creation:", timeCreateApi)  //maybe logg this

	startOfUserAPI := "sk-envdash-"

	// Generate hash of email + current time using md5
	//this will be used as the api key for the user, and will be unique for each registration
	//unique even, even same email cant make same key, because of the time component
	hash := md5.Sum([]byte(email + time.Now().String()))
	hashString := hex.EncodeToString(hash[:])
	createAPI := startOfUserAPI + hashString

	// Display the character
	fmt.Println("createAPI:", createAPI)

	return createAPI, timeCreateApi
}

/*
Checks if the email provided is valid, if so return true
*/
func isValidEmail(email string) bool {
	address, err := mail.ParseAddress(email)

	if err != nil {
		return false
	}

	return address != nil
}

func (h *Handler) DeleteAuth(w http.ResponseWriter, r *http.Request) {
	//used in handling connection to Firestore
	ctx := r.Context()

	if r.Method != http.MethodDelete { //if not a DELETE request, return method not allowed
		http.Error(w, "Only POST method allowed", http.StatusMethodNotAllowed)
		return
	}

	API := r.PathValue("id")
	//Checks if api key exists
	if !h.store.ApiKeyExists(ctx, API) {
		http.Error(w, "could not find API key", http.StatusNotFound)
		return
	}

	//we have to delete this key in firestore
	err := h.store.DeleteAPIkey(ctx, API)
	if err != nil {
		http.Error(w, "something went wrong in Firestore, while trying to delete apikey", http.StatusInternalServerError)
		return
	}

	//if it goes through, it works
	w.WriteHeader(http.StatusNoContent)

}
